# https://artifacthub.io/packages/helm/ot-container-kit/redis?modal=values
redisExporter:
  enabled: true
  env:
  - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
    value: "true"
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: redis-instance
